Repository Here-You/FrontEnd, pull requests merged in 2024-01, with the labels that each got.

#17 [Feat] : 시그니처 기록 페이지 구현
  public/images/location.svg
  public/images/signaturewriteOption1.svg
  public/images/signaturewriteOption2.svg
  public/images/signaturewriteOption3.svg
  public/mockServiceWorker.js
  src/index.css
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Editor.style.js
  src/pages/signature/write/SignatureWrite.jsx
Labels: ✨ Feature

#4 [Feat]:온보딩
  public/images/onboarding1.svg
  public/images/onboarding2.svg
  public/images/onboarding3.svg
  public/images/onboarding4.svg
  src/components/onboarding/OnBoardingCard.jsx
  src/components/onboarding/OnBoardingCard.style.js
  src/pages/AppLayout.jsx
  src/pages/index.jsx
  src/pages/onboarding/OnBoarding.jsx
  src/pages/onboarding/OnBoardingPage.jsx
  src/pages/onboarding/OnBoardingPage.style.js
Labels: ✨ Feature

#16 [Feat] : 메이트 전체 페이지 구현
  public/images/mateRule_check.svg
  public/images/mateRule_write.svg
  public/images/mateSearch.svg
  public/images/mate_management.svg
  public/images/mate_search.svg
  public/images/userImg.png
  src/App.jsx
  src/apis/request/mate.js
  src/components/mate/Card.jsx
  src/components/mate/Card.style.js
  src/components/mate/FollowBox.jsx
  src/components/mate/Profile.jsx
  src/components/mate/Profile.style.js
  src/components/mate/Search.jsx
  src/components/mate/Search.style.js
  src/components/mate/Title.jsx
  src/components/mate/Title.style.js
  src/constants/path.js
  src/mocks/handlers/index.js
  src/mocks/handlers/mate-look.js
  src/mocks/handlers/mate-search-result.js
  src/pages/index.jsx
  src/pages/mate/Mate.jsx
  src/pages/mate/home/MateHome.jsx
  src/pages/mate/home/MateHome.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
  src/pages/mate/management/MateManagement.style.js
  src/pages/mate/search/MateSearch.jsx
Labels: ✨ Feature, 🌟다빈

#23 [Feat] : 사용자 테스트 UI 구현
  public/images/japan.svg
  public/images/mainlogo.svg
  public/images/spacelogo.svg
  src/App.jsx
  src/layout/TravelLayout.jsx
  src/layout/index.js
  src/pages/traveltype/TestData.js
  src/pages/traveltype/TravelType.jsx
  src/pages/traveltype/TravelType.style.js
  src/pages/traveltype/TypeTest.jsx
  src/pages/traveltype/TypeTest.style.js
  src/pages/traveltype/result/TravelType.style.js
  src/pages/traveltype/result/TravelTypeResult.jsx
Labels: ✨ Feature, 🪐수진

#12 [Feat]: 마이페이지 메인 구현
  index.html
  public/User.svg
  public/images/mypage/Book.svg
  public/images/mypage/Bug.svg
  public/images/mypage/Chat.svg
  public/images/mypage/Close_round_light.svg
  public/images/mypage/Diamond.svg
  public/images/mypage/Expand_right_light.svg
  public/images/mypage/File_dock_light.svg
  public/images/mypage/Lock.svg
  public/images/mypage/MyPageLogo.svg
  public/images/mypage/Question.svg
  public/images/mypage/Sertificate_light.svg
  public/images/mypage/Sign_out_squre.svg
  public/images/mypage/User_cicrle_light.svg
  public/images/mypage/index.js
  src/apis/request/profile.js
  src/components/ModalPortal.jsx
  src/components/mypage/Category.jsx
  src/components/mypage/MypageInfo.jsx
  src/components/mypage/MypageInfo.style.js
  src/components/mypage/SubCateGoryPage.jsx
  src/components/mypage/SubCateGoryPage.style.js
  src/components/mypage/edit/EditModal.jsx
  src/components/mypage/edit/EditModalPage.style.js
  src/components/mypage/edit/MyProfileEdit.jsx
  src/components/mypage/edit/MyProfileEditContainer.jsx
  src/components/mypage/edit/MyProfileEditContainer.style.js
  src/constants/editModal.js
  src/constants/editPage.js
  src/constants/path.js
  src/constants/subcategory.js
  src/main.jsx
  src/mocks/handlers/index.js
  src/mocks/handlers/profile-info.js
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/MyPage.style.js
  src/pages/mypage/edit/MyPageEdit.jsx
  src/pages/mypage/edit/MyPageEdit.style.js
  src/store/editModal.js
  src/theme.jsx
Labels: ✨ Feature, 🐾준하

#13 [Feat] : 시그니처 메인페이지 구현
  public/images/signature/ClickedHeart.svg
  public/images/signature/NoneClickHeart.svg
  public/images/signature/editButton.svg
  public/images/signature/plusButton.svg
  src/apis/request/preview.js
  src/constants/path.js
  src/mocks/handlers/PreviewHandler.js
  src/mocks/handlers/index.js
  src/pages/signature/Signature.jsx
  src/pages/signature/components/SignaturePreview.jsx
  src/pages/signature/components/SignatureTag.jsx
  src/pages/signature/edit/SignatureEdit.jsx
  src/pages/signature/main/Content.jsx
  src/pages/signature/main/LikeContent.jsx
  src/pages/signature/main/Message.jsx
  src/pages/signature/main/MySignature.jsx
  src/pages/signature/main/RecContent.jsx
Labels: ✨ Feature, 🪐수진

#35 Feature/#14
  src/components/login/LoginButton.jsx
  src/components/login/LoginButton.style.js
  src/components/signup/SignUpMyInfo.jsx
  src/components/signup/SignUpMyInfo.style.js
  src/constants/login.js
  src/pages/login/Login.jsx
  src/pages/login/Login.style.js
  src/pages/signup/SignUp.jsx
  src/pages/signup/SignUp.style.js
Labels: ✨ Feature, 🐾준하

#30 [Feat] : 시그니처 메인페이지, 각 시그니처 페이지 구현
  public/images/PreviousButton.svg
  public/images/bookImg.svg
  public/images/locationImg.svg
  public/images/nextButton.svg
  src/constants/path.js
  src/mocks/handlers/index.js
  src/mocks/handlers/previewHandlers.js
  src/pages/signature/Signature.jsx
  src/pages/signature/SignaturePage.jsx
  src/pages/signature/SignaturePage.style.js
  src/pages/signature/components/Banner.jsx
  src/pages/signature/components/Banner.style.js
  src/pages/signature/components/Preview.jsx
  src/pages/signature/components/Preview.style.js
  src/pages/signature/edit/SignatureEdit.jsx
  src/pages/signature/main/MySignaturePage.jsx
  src/pages/signature/main/MySignaturePage.style.js
  src/pages/signature/main/NoSignature.jsx
  src/pages/signature/main/NoSignature.style.js
  src/pages/signature/main/TotalSignature.jsx
  src/pages/signature/main/TotalSignature.style.js
Labels: ✨ Feature, 🪐수진

#31 [Feat] : 메이트 파트 중 여행 규칙 관련 페이지 구현
  public/images/add-user.svg
  public/images/text-center-black.svg
  public/images/text-center-green.svg
  public/images/text-justify-black.svg
  public/images/text-justify-green.svg
  public/images/text-left-black.svg
  public/images/text-left-green.svg
  public/images/text-right-black.svg
  public/images/text-right-green.svg
  src/App.jsx
  src/apis/request/mate.js
  src/components/mate/DropDown.jsx
  src/components/mate/DropDown.style.js
  src/components/mate/RuleButton.jsx
  src/components/mate/RuleButton.style.js
  src/components/mate/TeamContainer.jsx
  src/components/mate/TeamContainer.style.js
  src/constants/path.js
  src/pages/index.jsx
  src/pages/mate/Mate.jsx
  src/pages/mate/rule/MateRuleCheck.jsx
  src/pages/mate/ruleCheck/MateRuleCheck.jsx
  src/pages/mate/ruleCheck/MateRuleCheck.style.js
  src/pages/mate/ruleWrite/MateRuleWrite.jsx
  src/pages/mate/ruleWrite/MateRuleWrite.style.js
Labels: ✨ Feature, 🌟다빈

#37 Feat : 구글 로그인, 카카오 로그인 구현
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KakaoLoginButton.jsx
  src/components/login/LoginButton.jsx
  src/components/login/SnsLoginButton.style.js
  src/pages/login/Login.jsx
  src/pages/login/Login.style.js
Labels: ✨ Feature, 🐾준하

#40 [Feat] : 시그니처 기록 페이지 구현
  public/icons/leftIcon.svg
  public/icons/rightIcon.svg
  public/images/addButton.svg
  src/mocks/handlers/index.js
  src/pages/signature/Signature.jsx
  src/pages/signature/edit/SignatureEdit.jsx
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Editor.style.js
  src/pages/signature/write/Page.jsx
  src/store/useSignatureWrite.jsx
Labels: ✨ Feature, 🪐수진

#49 [Feat]: Calendar 기능 개발 #36
  package.json
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/journey/Journey.style.js
  src/components/map/TravelMap.jsx
  src/constants/path.js
  src/index.css
  src/mocks/handlers/calendar.js
  src/pages/AppLayout.jsx
  src/pages/home/Home.style.js
  src/pages/map/Map.style.js
Labels: ✨ Feature, 📬 API, 👑용민

#48 [Feat] : dailyrecord page 반응형, 아이콘 기능 구현
  public/icons/Angry.svg
  public/icons/Cloud.svg
  public/icons/CloudLight.svg
  public/icons/Happy.svg
  public/icons/Lol.svg
  public/icons/Rain.svg
  public/icons/Sad.svg
  public/icons/Sun.svg
  public/icons/Winter.svg
  public/icons/Wow.svg
  src/components/SelectBox/IconSelectBox/IconSelectBox.jsx
  src/components/SelectBox/IconSelectBox/IconSelectBox.style.js
  src/constants/dailyRecord.js
  src/pages/dailyRecord/DailyRecordPage.style.js
  src/pages/dailyRecord/edit/DailyRecordEdit.style.js
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/dailyRecord/write/DailyRecordWritePage.style.js
Labels: ✨ Feature, 🎨 Html&css, 💗다인

#54 [ Feat ] : MainPage MSW 연결
  src/App.jsx
  src/apis/request/home.js
  src/apis/request/map.js
  src/components/bottomSheet/BottomDetailScrollPage.jsx
  src/components/bottomSheet/BottomDetailScrollPage.style.js
  src/components/bottomSheet/BottomScrollPage.jsx
  src/components/bottomSheet/BottomScrollPage.style.js
  src/components/bottomSheet/bottomTravelList/BottomTravelList.jsx
  src/components/bottomSheet/bottomTravelList/BottomTravelList.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/map/TravelMapDetail.jsx
  src/components/map/TravelMapDetail.style.js
  src/constants/path.js
  src/hooks/home/useGetJourneyMap.js
  src/hooks/home/useLoadMonthlyJourney.js
  src/hooks/home/useMonthlyJourney.js
  src/mocks/handlers/home.js
  src/pages/home/Home.jsx
  src/pages/index.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/detail/MapDetailPage.jsx
Labels: ✨ Feature, 📬 API, ✅ Test, 👑용민

#52 [ Feat ] : dailyrecord, dailyrecord write page msw, selectBox
  public/icons/CloudLight.svg
  public/icons/Wow.svg
  src/components/SelectBox/IconSelectBox/IconSelectBox.jsx
  src/components/SelectBox/IconSelectBox/IconSelectBox.style.js
  src/components/journey/Journey.jsx
  src/components/journey/Journey.style.js
  src/constants/path.js
  src/pages/dailyRecord/DailyRecordPage.jsx
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/dailyRecord/write/DailyRecordWritePage.style.js
Labels: ✨ Feature, ✅ Test, 💗다인

#56 [Feat] : schedules component msw 연결 및 기능 구현
  package.json
  public/icons/EditLight.svg
  public/icons/File.svg
  public/icons/LocationLight.svg
  public/icons/Trash.svg
  src/apis/request/home.js
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/index.js
  src/components/journey/Journey.jsx
  src/components/journey/detail/DetailPlan.jsx
  src/components/schedules/Schedules.jsx
  src/components/schedules/Schedules.style.js
  src/components/schedules/detail/DetailPlan.jsx
  src/components/schedules/detail/DetailPlan.style.js
  src/components/schedules/mutations.js
  src/components/searchMap/SearchMap.jsx
  src/mocks/handlers/home.js
  src/pages/dailyRecord/DailyRecordPage.jsx
  src/pages/dailyRecord/DailyRecordPage.style.js
  src/pages/home/Home.jsx
Labels: ✨ Feature, 💗다인
