Repository Here-You/FrontEnd, pull requests merged in 2024-02, with the labels that each got.

#63 [Feat] : journey Modal 구현 및 msw 연결
  src/apis/request/home.js
  src/components/calendar/TravelCalendar.jsx
  src/components/modal/Modal.jsx
  src/components/modal/Modal.style.js
  src/components/modal/journeyEdit/JourneyEdit.style.js
  src/components/modal/journeyEdit/JourneyEditModal.jsx
  src/components/modal/journeyWriteModal/JourneyWriteModal.jsx
  src/components/modal/journeyWriteModal/JourneyWriteModal.style.js
  src/hooks/modal/useJourneyEditModal.js
  src/hooks/modal/useJourneyWriteModal.js
  src/pages/home/Home.jsx
  src/pages/home/Home.style.js
Labels: ✨ Feature, 📬 API, 💗다인

#66 Feat : 시그니처, 탐색 페이지 구현
  public/images/explore/nonHeart.svg
  public/images/explore/searchIcon.svg
  src/App.jsx
  src/components/explore/Preview.jsx
  src/components/explore/Recent.jsx
  src/components/explore/Search.jsx
  src/components/explore/SearchResult.jsx
  src/components/explore/Trending.jsx
  src/components/footer/Footer.jsx
  src/constants/path.js
  src/mocks/handlers/PreviewHandler.js
  src/mocks/handlers/index.js
  src/pages/explore/ExplorePage.jsx
  src/pages/explore/search/ExploreSearch.jsx
  src/pages/index.jsx
Labels: ✨ Feature, 🪐수진

#67 Feat: 달력 여정 수정, 여정 추가 modal 연결 및 Home 버튼 반응형
  src/components/SelectBox/IconSelectBox/IconSelectBox.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/modal/Modal.style.js
  src/components/modal/journeyEdit/JourneyEditModal.jsx
  src/components/schedules/Schedules.style.js
  src/pages/dailyRecord/write/DailyRecordWritePage.style.js
  src/pages/home/Home.jsx
  src/pages/home/Home.style.js
Labels: ✨ Feature, 🎨 Html&css, 💗다인

#71 Feature/#69
  public/images/Book_light.svg
  public/images/comment_light.svg
  public/images/loginBefore.svg
  public/images/mypage/MyPageLogo.jpg
  public/images/mypage/index.js
  src/App.jsx
  src/apis/request/profile.js
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KaKaoLogout.jsx
  src/components/login/LoginBefore/LoginBefore.jsx
  src/components/login/LoginBefore/LoginBefore.style.js
  src/components/login/LoginButton.jsx
  src/components/mypage/MypageInfo.jsx
  src/components/mypage/MypageInfo.style.js
  src/components/mypage/SubCateGoryPage.jsx
  src/components/mypage/SubCateGoryPage.style.js
  src/components/mypage/edit/MyProfileEditContainer.jsx
  src/components/mypage/edit/MyProfileEditContainer.style.js
  src/components/navbar/Navbar.jsx
  src/components/notification/NotificatiionPage.style.js
  src/components/notification/NotificationPage.jsx
  src/constants/editModal.js
  src/constants/path.js
  src/constants/subcategory.js
  src/hooks/login/ useKaKaoToken.js
  src/mocks/handlers/profile.js
  src/pages/index.jsx
  src/pages/login/Login.jsx
  src/pages/login/LoginBeforePage.jsx
  src/pages/login/LoginBeforePage.style.js
  src/pages/login/Redirect.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/edit/MyPageEdit.jsx
  src/pages/mypage/edit/MyPageEdit.style.js
  src/pages/notification/Notification.jsx
  src/pages/notification/Notification.style.js
Labels: ✨ Feature, 📃 Docs, 🐾준하

#73 [Feat] : Home addButton style, dailyrecord edit page msw 연결
  src/apis/request/home.js
  src/components/SelectBox/IconSelectBox/IconSelectBox.jsx
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/schedules/Schedules.jsx
  src/constants/path.js
  src/hooks/home/useGetDiary.js
  src/mocks/handlers/home.js
  src/pages/dailyRecord/DailyRecordPage.jsx
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.style.js
Labels: ✨ Feature, 🐞 BugFix, 💗다인

#79 [Feat] : 메이트 페이지 Infinite Scroll 구현
  src/components/mate/Banner.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
Labels: ✨ Feature, 📬 API, 👑용민

#74 [Feat]: msw연결 유효성검사
  package.json
  src/apis/request/profile.js
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KakaoLoginButton.jsx
  src/components/modal/mypage/IntroEditModal.jsx
  src/components/modal/mypage/IntroEditModal.style.js
  src/components/modal/mypage/LogoutModal.jsx
  src/components/modal/mypage/LogoutModal.style.js
  src/components/modal/mypage/NicknameEdit.style.js
  src/components/modal/mypage/NicknameEditModal.jsx
  src/components/modal/mypage/WithDrawalModal.jsx
  src/components/modal/mypage/WithDrawalModal.style.js
  src/components/mypage/SubCateGoryPage.jsx
  src/components/mypage/SubCateGoryPage.style.js
  src/components/mypage/edit/EditModal.jsx
  src/components/mypage/edit/EditModalPage.style.js
  src/components/mypage/edit/MyProfileEditContainer.jsx
  src/components/schema/Schema.jsx
  src/components/signup/SignUpMyInfo.jsx
  src/components/signup/SignUpMyInfo.style.js
  src/constants/path.js
  src/constants/subcategory.js
  src/hooks/modal/useIntroEditModal.js
  src/hooks/modal/useLogoutModal.js
  src/hooks/modal/useNickameEditModal.js
  src/hooks/modal/useWithdrawalModal.js
  src/mocks/handlers/profile.js
  src/pages/login/Redirect.jsx
Labels: ✨ Feature, 🐾준하

#86 [Bug] : 충돌 에러 수정
  src/apis/request/mate.js
  src/components/mate/ParticipantMate.style.js
  src/components/mate/RuleBox.jsx
  src/components/mate/RuleBox.style.js
  src/components/mate/RuleBoxCheck.style.js
  src/components/mate/Search.jsx
  src/pages/mate/Mate.jsx
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/search/MateSearch.jsx
Labels: 🐞 BugFix

#90 [Feat]: 시그니처 msw연결
  jsconfig.json
  package.json
  src/constants/path.js
  src/hooks/signature/useDeleteMySignature.js
  src/hooks/signature/useGetDetail.js
  src/hooks/signature/useLikeSignature.js
  src/hooks/signature/usePostNewSignature .js
  src/hooks/signature/useSignature.js
  src/hooks/signature/useSignaturePreview .js
  src/hooks/signature/useUpdateMySignature.js
  src/mocks/handlers/signature.js
  src/pages/login/Login.jsx
  src/pages/signature/Signature.jsx
  src/pages/signature/components/Preview.jsx
  src/pages/signature/components/Preview.style.js
  src/pages/signature/main/MySignaturePage.jsx
  src/pages/signature/main/MySignaturePage.style.js
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/post/SignaturePost.style.js
Labels: ✨ Feature, 🐾준하

#95 [Feat]: 탐색 페이지 전체 수정 #93
  src/App.jsx
  src/apis/api.js
  src/apis/request/search.js
  src/components/explore/Preview.jsx
  src/components/explore/PreviewStyle.style.js
  src/components/explore/Recent.jsx
  src/components/explore/SearchResult.jsx
  src/components/explore/SignatureSearchSlider.jsx
  src/components/explore/SignatureSearchSlider.style.js
  src/components/explore/Trending.jsx
  src/components/footer/Footer.jsx
  src/components/footer/Footer.style.js
  src/hooks/search/useSearch.js
  src/hooks/search/useSearchKeyWord.js
  src/mocks/handlers/explore.js
  src/pages/explore/ExplorePage.jsx
  src/pages/explore/ExplorePage.style.js
  src/pages/explore/search/ExploreSearch.jsx
  src/pages/index.jsx
  src/pages/signature/Signature.jsx
  src/pages/signature/SignaturePage.jsx
  src/pages/signature/main/MySignature.jsx
  src/pages/signature/main/RecContent.jsx
  src/pages/signature/main/TotalSignature.jsx
Labels: ✨ Feature, 📬 API, 👑용민

#94 [Feat] : signature WritePage style 수정
  public/icons/PinLight.svg
  src/apis/request/signature.js
  src/components/searchMap/SearchMap.jsx
  src/pages/signature/SignaturePage.jsx
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Editor.style.js
  src/pages/signature/write/Page.jsx
  src/store/useSignatureWrite.jsx
Labels: ✨ Feature, 💗다인

#99 [Feat] : 탐색 페이지 / 시그니처 디테일 페이지 스타일링 변경, 하트 컴포넌트 제작, msw 연결
  package.json
  src/components/HeartButton/HeartButton.jsx
  src/components/HeartButton/HeartButton.style.js
  src/mocks/handlers/signature.js
  src/pages/AppLayout.jsx
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/post/SignaturePost.style.js
Labels: ✨ Feature, 📬 API, 👑용민

#101 [Feat]: 구글, 카카오 로그인, 마이페이지 필요없는 파일 삭제, 로그아웃
  src/App.jsx
  src/apis/request/notification.js
  src/apis/request/profile.js
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KaKaoLogout.jsx
  src/components/login/LoginBefore/LoginBefore.jsx
  src/components/login/LoginBefore/LoginBefore.style.js
  src/components/modal/Modal.jsx
  src/components/modal/Modal.style.js
  src/components/modal/mypage/IntroEditModal.jsx
  src/components/modal/mypage/LogoutModal.jsx
  src/components/modal/mypage/NicknameEditModal.jsx
  src/components/modal/mypage/WithDrawalModal.jsx
  src/components/notification/NotificationPage.jsx
  src/components/schema/Schema.jsx
  src/constants/subcategory.js
  src/hooks/notification/useNotification.js
  src/mocks/handlers/index.js
  src/mocks/handlers/notification.js
  src/pages/index.jsx
  src/pages/login/LoginBeforePage.jsx
  src/pages/login/LoginBeforePage.style.js
  src/pages/login/Redirect.jsx
  src/pages/mypage/password/MyPagePassword.jsx
  src/pages/mypage/withdraw/MyPageWithdraw.jsx
Labels: ✨ Feature, 🐾준하

#103 [Style] : handler 안 쓰는 핸들러 정리 및 삭제 / 데이터에 따라 깨지는 style 확인
  public/images/mypage/index.js
  src/App.jsx
  src/components/banner/Banner.jsx
  src/components/banner/Banner.style.js
  src/components/preview/Preview.jsx
  src/components/preview/Preview.style.js
  src/components/preview/signature/SignaturePreview.jsx
  src/components/preview/signature/SignatureTag.jsx
  src/mocks/handlers/MateInviteHandlers.js
  src/mocks/handlers/MateRuleDetailCheckHandlers.js
  src/mocks/handlers/MateRuleListHandlers.js
  src/mocks/handlers/PreviewHandlers2.js
  src/mocks/handlers/calendar.js
  src/mocks/handlers/index.js
  src/mocks/handlers/mate-look.js
  src/mocks/handlers/mate-management.js
  src/mocks/handlers/mate-search-result.js
  src/mocks/handlers/mate.js
  src/mocks/handlers/notification.js
  src/mocks/handlers/profile-info.js
  src/mocks/handlers/profile.js
  src/mocks/handlers/search.js
  src/mocks/handlers/travel-place.js
  src/pages/index.jsx
  src/pages/signature/SignaturePage.jsx
  src/pages/signature/main/Content.jsx
  src/pages/signature/main/LikeContent.jsx
  src/pages/signature/main/Message.jsx
  src/pages/signature/main/MySignaturePage.jsx
  src/pages/signature/main/RecContent.jsx
  src/pages/signature/popular/SignaturePopular.jsx
  src/pages/signature/recommend/SignatureRecommend.jsx
  src/pages/signature/search/SignatureSearch.jsx
Labels: 🐞 BugFix, 💗다인

#91 [Style] : 메이트 반응형 디자인 + msw 연결 재정리 !MERGE 금지!
  public/images/mate/mateSearch.svg
  src/apis/request/mate.js
  src/components/calendar/TravelCalendar.jsx
  src/components/comment/Comment.jsx
  src/components/comment/Comment.style.js
  src/components/index.js
  src/components/mate/Card.style.js
  src/components/mate/ExitModal.style.js
  src/components/mate/FollowBox.jsx
  src/components/mate/FollowModal.style.js
  src/components/mate/ParticipantMate.jsx
  src/components/mate/ParticipantMate.style.js
  src/components/mate/ParticipantModal.jsx
  src/components/mate/ParticipantModal.style.js
  src/components/mate/Profile.jsx
  src/components/mate/Profile.style.js
  src/components/mate/RuleBox.jsx
  src/components/mate/RuleBox.style.js
  src/components/mate/RuleBoxCheck.jsx
  src/components/mate/RuleBoxCheck.style.js
  src/components/mate/RuleComments.jsx
  src/components/mate/RuleComments.style.js
  src/components/mate/RuleSearchResult.jsx
  src/components/mate/RuleSearchResult.style.js
  src/components/mate/Search.style.js
  src/components/mate/SearchInviteMateModal.jsx
  src/components/mate/SearchInviteMateModal.style.js
  src/components/mate/TeamContainer.jsx
  src/components/mate/TeamContainer.style.js
  src/components/mate/Title.jsx
  src/components/mate/Title.style.js
  src/components/modal/inviteMatesModal/InviteMatesModal.jsx
  src/components/modal/inviteMatesModal/InviteMatesModal.style.js
  src/constants/path.js
  src/hooks/mate/useMateFollower.js
  src/hooks/mate/useParticipateTeamMate.js
  src/hooks/mate/useSearchMate.js
  src/hooks/mate/useTeamMateRule.js
  src/hooks/mate/useTeamRuleList.js
  src/hooks/modal/useInviteMatesModal.js
  src/hooks/useDebounce.js
  src/mocks/handlers/mate.js
  src/pages/mate/Mate.jsx
  src/pages/mate/Mate.style.js
  src/pages/mate/MateContainer.jsx
  src/pages/mate/main/MateMain.jsx
  src/pages/mate/main/MateMain.style.js
  src/pages/mate/management/MateManagement.jsx
  src/pages/mate/ruleCheck/MateRuleCheck.jsx
  src/pages/mate/ruleCheck/MateRuleCheck.style.js
  src/pages/mate/ruleCheck/MateRuleDetailCheck.jsx
  src/pages/mate/ruleCheck/MateRuleDetailCheck.style.js
  src/pages/mate/ruleWrite/MateRuleWrite.jsx
  src/pages/mate/ruleWrite/MateRuleWrite.style.js
  src/pages/mate/search/MateSearch.jsx
  src/pages/mate/search/MateSearch.style.js
  src/store/matesStore.js
  src/utils/date.js
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🌟다빈

#112 [Feat]: 이미지 업로드, 메이트 페이지 msw 연결, 시그니처 페이지 msw 연결, 도메인 연결
  index.html
  src/apis/request/mate.js
  src/components/mate/TeamContainer.jsx
  src/components/searchMap/SearchMap.jsx
  src/hooks/mate/useTeamRuleList.js
  src/mocks/handlers/mate.js
  src/pages/mate/ruleCheck/MateRuleCheck.jsx
  src/pages/mate/ruleCheck/MateRuleDetailCheck.jsx
  src/pages/mate/ruleWrite/MateRuleWrite.jsx
  src/pages/signature/edit/Page.jsx
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Page.jsx
Labels: ✨ Feature, 🌏 Deploy, 🐞 BugFix, ✅ Test, 👑용민

#113 [Feat] : 안 쓰는 경로 수정, home/map 페이지 에러 처리, home handler 수정
  src/apis/request/home.js
  src/apis/request/map.js
  src/components/bottomSheet/BottomJourneyDetailScrollPage.jsx
  src/components/bottomSheet/BottomScrollPage.jsx
  src/components/bottomSheet/BottomScrollPage.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/schedules/detail/DetailPlan.jsx
  src/constants/path.js
  src/hooks/home/useLoadMonthlyJourney.js
  src/mocks/handlers/home.js
  src/pages/dailyRecord/DailyRecordPage.jsx
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/detail/MapDetailPage.jsx
Labels: ✨ Feature, 🐞 BugFix, 💗다인

#115 [Feat]: Search[탐색]페이지 서버 연결 완성.
  netlify.toml
  public/_redirects
  src/apis/request/search.js
  src/components/explore/Preview.jsx
  src/components/explore/Search.jsx
  src/components/explore/SignatureSearchSlider.jsx
  src/hooks/image/useHandleImageChange.js
  src/hooks/search/useSearchExploreKeyword.js
  src/hooks/search/useSearchExploreMain.js
  src/pages/explore/ExplorePage.jsx
  src/pages/explore/ExplorePage.style.js
  src/pages/signature/edit/Page.jsx
  src/pages/signature/write/Page.jsx
Labels: ✨ Feature, 🌏 Deploy, 🐞 BugFix, 📬 API, ✅ Test, 👑용민

#122 [Feat] : mate comment 컴포넌트 무한스크롤 구현, mate comment input
  src/apis/request/mate.js
  src/components/comment/mate/MateCommentList.jsx
  src/components/comment/mate/MateCommentList.style.js
  src/components/comment/mate/commentInput/MateCommentInput.jsx
  src/components/comment/mate/commentInput/MateCommentInput.style.js
  src/components/comment/mate/commentView/MateCommentView.jsx
  src/components/comment/mate/commentView/MateCommentView.style.js
  src/constants/path.js
  src/mocks/handlers/mate.js
  src/pages/mate/ruleCheck/MateRuleDetailCheck.jsx
  src/pages/mate/ruleCheck/MateRuleDetailCheck.style.js
Labels: ✨ Feature, 💗다인

#128 [FEAT] Lazy Loading, Skeleton UI 적용, 기타 스타일 수정, ellipsis 적용.
  package.json
  src/components/explore/Preview.jsx
  src/components/explore/PreviewStyle.style.js
  src/components/mate/FollowButton.style.js
  src/components/mate/ManagementProfile.jsx
  src/components/mate/ManagementProfile.style.js
  src/components/mate/MateBox.style.js
  src/components/mate/skeleton/ManagementProfileSkeleton.jsx
  src/components/mate/skeleton/ManagementProfileSkeleton.style.js
  src/components/preview/Preview.jsx
  src/components/preview/Preview.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/management/MateManagement.jsx
  src/pages/mate/ruleCheck/MateRuleCheck.jsx
  src/pages/signature/main/MySignaturePage.jsx
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/write/Editor.style.js
  src/pages/signature/write/Page.jsx
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix, 📬 API, 👑용민

#126 [Feat] : Footer 시그니처 아이콘, Navbar 알림, 마이페이지 아이콘 수정
  public/images/footerSignature.svg
  src/components/footer/Footer.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.style.js
Labels: 🎨 Html&css, 🪐수진

#118 Feat: 하루일지 페이지 api 연결, routing, page path 변경
  src/App.jsx
  src/apis/request/home.js
  src/components/SelectBox/IconSelectBox/IconSelectBox.jsx
  src/components/schedules/Schedules.jsx
  src/components/schedules/detail/DetailPlan.jsx
  src/components/schedules/detail/DetailPlan.style.js
  src/constants/path.js
  src/hooks/home/useGetDiary.js
  src/mocks/handlers/home.js
  src/pages/dailyRecord/DailyRecordPage.jsx
  src/pages/dailyRecord/DailyRecordPage.style.js
  src/pages/dailyRecord/List/DailyRecordListPage.jsx
  src/pages/dailyRecord/List/DailyRecordListPage.style.js
  src/pages/dailyRecord/edit/DailyRecordEdit.style.js
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/dailyRecord/write/DailyRecordWritePage.style.js
  src/pages/index.jsx
Labels: ✨ Feature, 🐞 BugFix, 💗다인

#130 [Feat] : Home 달력 및 schedule 컴포넌트 api 연결/map 페이지 수정
  src/apis/request/home.js
  src/components/bottomSheet/BottomDetailScrollPage.jsx
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/schedules/Schedules.jsx
  src/components/schedules/SchedulesView.jsx
  src/components/schedules/SchedulesView.style.js
  src/components/schedules/detail/DetailPlan.jsx
  src/components/schedules/detail/DetailPlan.style.js
  src/hooks/home/useGetJourneyMap.js
  src/pages/home/Home.jsx
  src/pages/journey/JourneyDetail.jsx
Labels: ✨ Feature, 💗다인

#132 [Feat] : 하루일지 로직/api 수정 및 map 좌표 연결
  src/apis/request/home.js
  src/components/bottomSheet/BottomDetailScrollPage.jsx
  src/components/bottomSheet/BottomJourneyDetailScrollPage.jsx
  src/components/bottomSheet/BottomScrollPage.jsx
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/map/TravelMap.jsx
  src/components/map/TravelMapDetail.jsx
  src/components/modal/journeyEdit/JourneyEditModal.jsx
  src/components/modal/journeyWriteModal/JourneyWriteModal.jsx
  src/components/schedules/Schedules.jsx
  src/components/schedules/Schedules.style.js
  src/components/schedules/SchedulesView.jsx
  src/pages/dailyRecord/DailyRecordPage.style.js
  src/pages/dailyRecord/List/DailyRecordListPage.jsx
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/home/Home.style.js
  src/pages/journey/JourneyDetail.jsx
  src/pages/map/MapPage.jsx
Labels: ✨ Feature, 🐞 BugFix, 💗다인

#134 Feat: 시그니처 페이지 댓글 UI 구현
  src/components/comment/signature/SignatureCommentList.jsx
  src/components/comment/signature/SignatureCommentList.style.js
  src/components/comment/signature/commentInput/SignatureCommentInput.jsx
  src/components/comment/signature/commentInput/SignatureInput.style.js
  src/components/comment/signature/commentView/SignatureComment.jsx
  src/components/comment/signature/commentView/SignatureComment.style.js
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/post/SignaturePost.style.js
Labels: 🎨 Html&css, 💗다인

#138 Bug: schedule 컴포넌트 무한스크롤 버그 해결
  src/components/bottomSheet/BottomDetailScrollPage.jsx
  src/components/schedules/SchedulesView.jsx
Labels: 🐞 BugFix, 💗다인

#142 [Feat] : 메인페이지 구현
  public/images/main/calendar.svg
  public/images/main/fire.svg
  public/images/main/hereyouFont.svg
  public/images/main/logo.svg
  public/images/main/map.svg
  public/images/main/mateIcon.svg
  public/images/main/mountain.svg
  public/images/main/profileImg.svg
  public/images/main/right.svg
  public/images/main/signatureIcon.svg
  src/App.jsx
  src/components/main/Box.jsx
  src/components/main/Box.style.js
  src/components/main/HereyouBanner.jsx
  src/components/main/HereyouBanner.style.js
  src/components/main/HotSignature.jsx
  src/components/main/HotSignature.style.js
  src/components/main/LoginBanner.jsx
  src/components/main/LoginBanner.style.js
  src/components/main/Main.style.js
  src/components/main/MapContainer.jsx
  src/components/main/MapContainer.style.js
  src/constants/path.js
  src/pages/index.jsx
  src/pages/main/MainPage.jsx
Labels: ✨ Feature, 🪐수진

#146 [FEAT]: 시그니처 페이지 댓글 대댓글 기능 구현
  src/apis/request/signature.js
  src/components/comment/mate/commentInput/MateCommentInput.jsx
  src/components/comment/signature/SignatureCommentList.jsx
  src/components/comment/signature/commentInput/SignatureCommentInput.jsx
  src/components/comment/signature/commentView/SignatureComment.jsx
  src/components/comment/signature/commentView/SignatureComment.style.js
  src/components/mate/TeamContainer.jsx
  src/hooks/signature/queries/useGetSignatureComments.js
  src/hooks/signature/useGetDetail.js
  src/pages/mate/ruleEdit/RuleEdit.jsx
Labels: ✨ Feature, 📬 API, 👑용민

#141 [Bug] 시그니처 수정, 확인, 작성 페이지 오류 해결
  src/components/searchMap/SearchMap.jsx
  src/pages/signature/edit/Editor.jsx
  src/pages/signature/edit/Page.jsx
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/post/SignaturePost.style.js
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Editor.style.js
  src/pages/signature/write/Page.jsx
  src/store/useSignatureWrite.jsx
Labels: 🐞 BugFix, 💗다인

#145 [Refactor] : 시그니처, 탐색 코드 수정
  src/components/explore/Search.jsx
  src/components/explore/SignatureSearchSlider.jsx
  src/components/explore/SignatureSearchSlider.style.js
  src/pages/signature/Signature.jsx
  src/pages/signature/main/MySignaturePage.jsx
  src/pages/signature/main/MySignaturePage.style.js
  src/pages/signature/main/NoSignature.jsx
  src/pages/signature/main/NoSignature.style.js
  src/pages/signature/main/TotalSignature.jsx
  src/pages/signature/main/TotalSignature.style.js
Labels: 🔨 Refactor, 🪐수진

#148 [FEAT]: 메인 페이지 라우팅 변경
  src/App.jsx
  src/components/main/Box.style.js
  src/components/main/HotSignature.jsx
  src/components/main/HotSignature.style.js
  src/components/main/LoginBanner.style.js
  src/components/main/MapContainer.jsx
  src/components/main/MapContainer.style.js
  src/constants/path.js
  src/pages/main/MainPage.jsx
Labels: ✨ Feature, 👑용민

#150 [Fix] : 시그니처, 탐색 페이지 이동 가려지는 거 수정
  src/components/comment/signature/SignatureCommentList.jsx
  src/pages/signature/post/SignaturePost.style.js
Labels: 🎨 Html&css, 🐞 BugFix, 🪐수진

#153 [Style] : 메인페이지 UI 수정
  src/components/main/Box.style.js
  src/components/main/LoginBanner.jsx
  src/components/main/LoginBanner.style.js
  src/components/main/MapContainer.jsx
  src/components/main/MapContainer.style.js
  src/pages/main/MainPage.jsx
  src/pages/main/Mainpage.style.js
Labels: 🎨 Html&css, 🪐수진

#155 [Bug] : calender, map, 하루일지 page 에러 해결
  src/components/bottomSheet/BottomDetailScrollPage.style.js
  src/components/bottomSheet/BottomScrollPage.style.js
  src/components/bottomSheet/bottomTravelList/BottomTravelList.jsx
  src/components/bottomSheet/bottomTravelList/BottomTravelList.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/map/TravelMap.jsx
  src/components/map/TravelMapDetail.jsx
  src/components/schedules/Schedules.jsx
  src/components/schedules/Schedules.style.js
  src/components/schedules/SchedulesView.jsx
  src/components/schedules/SchedulesView.style.js
  src/components/schedules/detail/DetailPlan.jsx
  src/components/searchMap/SearchMap.jsx
  src/pages/dailyRecord/List/DailyRecordListPage.jsx
  src/pages/dailyRecord/List/DailyRecordListPage.style.js
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/home/Home.jsx
  src/pages/map/Map.style.js
  src/pages/map/MapPage.jsx
Labels: 🐞 BugFix, 💗다인

#157 [Feat] 좋아요 누른 사람 모달 생성
  src/apis/request/mate.js
  src/apis/request/signature.js
  src/components/mate/FollowButton.jsx
  src/components/mate/FollowButton.style.js
  src/components/modal/Modal.style.js
  src/components/modal/likerFindModal/LikerFindModal.jsx
  src/components/modal/likerFindModal/LikerFindModal.style.js
  src/hooks/modal/useLikersModal.js
  src/hooks/signature/queries/useGetLikers.js
  src/hooks/signature/queries/useGetSignaturePost.js
  src/pages/mate/ruleEdit/RuleEdit.jsx
  src/pages/mypage/edit/MyPageEdit.jsx
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/post/SignaturePost.style.js
  src/store/matesStore.js
Labels: ✨ Feature

#162 [Feat] 시그니처 페이지 대댓글 구현 UX 개선
  src/apis/request/signature.js
  src/components/comment/signature/commentView/SignatureComment.jsx
  src/components/comment/signature/commentView/SignatureComment.style.js
  src/pages/signature/post/SignaturePost.jsx
Labels: ✨ Feature, 📬 API, 👑용민

#163 [Style] : mate, mypage(daily record), profile 반응형 수정
  src/App.jsx
  src/components/banner/BannerDiary.style.js
  src/components/comment/mate/MateCommentList.style.js
  src/components/comment/mate/commentInput/MateCommentInput.style.js
  src/components/mate/Banner.style.js
  src/components/mate/ManagementProfile.jsx
  src/components/mate/ManagementProfile.style.js
  src/components/mate/MateBox.jsx
  src/components/mate/MateBox.style.js
  src/components/mate/TeamContainer.style.js
  src/components/profile/CountInfo.style.js
  src/components/profile/ProfileBox.style.js
  src/pages/mate/Mate.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
  src/pages/mate/ruleCheck/MateRuleDetailCheck.style.js
  src/pages/mate/ruleEdit/RuleEdit.style.js
  src/pages/mate/ruleWrite/MateRuleWrite.style.js
  src/pages/mypage/diary/MyDiary.style.js
  src/pages/profile/ProfilePage.style.js
Labels: 🎨 Html&css, 💗다인

#170 [Style] : 메이트 탐색하기 Style 변경
  src/App.jsx
  src/components/mate/FollowButton2.jsx
  src/components/mate/MateBox.jsx
  src/components/mate/MateBox.style.js
  src/components/mate/MateRecsys.jsx
  src/components/mate/MateRecsys.style.js
  src/components/notification/NotificationPage.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
Labels: 🎨 Html&css, 🪐수진

#173 Feature/#172: 소셜로그인 마이페이지 메인페이지 반영 및 쿼리 리팩토링
  src/components/login/LoginButton.jsx
  src/components/main/LoginBanner.jsx
  src/components/main/LoginBanner.style.js
  src/components/modal/mypage/LogoutModal.jsx
  src/components/mypage/Category.jsx
  src/components/mypage/MypageInfo.jsx
  src/components/mypage/MypageInfo.style.js
  src/components/mypage/SubCateGoryPage.jsx
  src/constants/editPage.js
  src/constants/subcategory.js
  src/pages/login/Login.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/MyPage.style.js
  src/pages/mypage/edit/MyPageEdit.jsx
Labels: ✨ Feature, 📬 API, 👑용민

#179 feat: Persit Zustand Login 상태 관리
  src/store/useAuth.js
Labels: 🐞 BugFix

#178 [Style] : calendar, map, explore page 스켈레톤 UI 구현 / redirect page 구현
  public/images/RedirectIcon.png
  src/components/bottomSheet/BottomJourneyDetailScrollPage.jsx
  src/components/bottomSheet/BottomScrollPage.jsx
  src/components/bottomSheet/bottomTravelList/skeleton/BottomTravelListskeleton.jsx
  src/components/bottomSheet/bottomTravelList/skeleton/BottomTravelListskeleton.style.js
  src/components/bottomSheet/skeleton/BottomJourneyDetailScrollPageSkeleton.jsx
  src/components/bottomSheet/skeleton/BottomJourneyDetailScrollPageSkeleton.style.js
  src/components/bottomSheet/skeleton/HeaderSkeleton.jsx
  src/components/bottomSheet/skeleton/HeaderSkeleton.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/skeleton/CalendarSkeleton.jsx
  src/components/calendar/skeleton/CalendarSkeleton.style.js
  src/components/explore/skeleton/SignatureSearchPreviewSkeleton.jsx
  src/components/explore/skeleton/SignatureSearchPreviewSkeleton.style.js
  src/components/map/skeleton/MapSkeleton.jsx
  src/components/map/skeleton/MapSkeleton.style.js
  src/components/schedules/SchedulesView.jsx
  src/components/schedules/skeleton/SchedulesViewSkeleton.jsx
  src/components/schedules/skeleton/SchedulesViewSkeleton.style.js
  src/pages/explore/ExplorePage.jsx
  src/pages/login/Redirect.jsx
  src/pages/login/Redirect.style.js
  src/pages/map/MapPage.jsx
  src/pages/map/detail/MapDetailPage.jsx
Labels: 🎨 Html&css, 💗다인

#182 [Style] : toast로 모든 알림 변경, 시그니처 작성 오류 해결
  src/components/comment/mate/commentInput/MateCommentInput.jsx
  src/components/comment/mate/commentView/MateCommentView.jsx
  src/components/comment/signature/commentInput/SignatureCommentInput.jsx
  src/components/login/GoogleLoginButton.jsx
  src/components/mate/FollowButton.jsx
  src/components/mate/FollowButton2.jsx
  src/components/mate/TeamContainer.jsx
  src/components/modal/journeyEdit/JourneyEditModal.jsx
  src/components/modal/journeyWriteModal/JourneyWriteModal.jsx
  src/components/modal/likerFindModal/LikerFindModal.style.js
  src/components/modal/mypage/PublicScopeModal.jsx
  src/components/profile/ProfileBox.jsx
  src/components/schedules/Schedules.jsx
  src/components/schedules/detail/DetailPlan.jsx
  src/components/signup/SignUpMyInfo.jsx
  src/pages/dailyRecord/List/DailyRecordListPage.jsx
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/home/Home.jsx
  src/pages/login/Redirect.jsx
  src/pages/mate/Mate.jsx
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
  src/pages/signature/edit/Editor.jsx
  src/pages/signature/write/Editor.jsx
Labels: 🎨 Html&css, 💗다인

#183 [FEAT]: Signature Post, Comment 로그인 로직 수정
  src/components/comment/signature/commentInput/SignatureCommentInput.jsx
  src/components/comment/signature/commentView/SignatureComment.jsx
  src/pages/signature/post/SignaturePost.jsx
Labels: ✨ Feature, 🐞 BugFix, 👑용민

#186 [Style] : Signup UI 변경
  public/images/signupImg.svg
  src/components/mypage/edit/MyProfileContainer.style.js
  src/components/signup/SignUpMyInfo.jsx
  src/components/signup/SignUpMyInfo.style.js
  src/pages/signup/SignUp.jsx
  src/pages/signup/SignUp.style.js
Labels: 🎨 Html&css, 🪐수진

#189 [Style] : 시그니처 글 UI 변경
  public/images/pin.svg
  src/components/footer/Footer.jsx
  src/components/navbar/Navbar.style.js
  src/pages/signature/post/SignaturePost.jsx
  src/pages/signature/post/SignaturePost.style.js
Labels: 🎨 Html&css, 🪐수진

#190 [Feat]: 에러메시지
  src/components/comment/mate/commentInput/MateCommentInput.jsx
  src/components/comment/mate/commentView/MateCommentView.jsx
  src/components/comment/signature/commentInput/SignatureCommentInput.jsx
  src/components/comment/signature/commentView/SignatureComment.jsx
  src/components/mate/TeamContainer.jsx
  src/components/modal/likerFindModal/LikerFindModal.jsx
  src/components/modal/mypage/IntroEditModal.jsx
  src/components/modal/mypage/NicknameEditModal.jsx
  src/components/modal/mypage/WithDrawalModal.jsx
  src/components/profile/ProfileBox.jsx
  src/pages/mate/Mate.jsx
  src/pages/signature/post/SignaturePost.jsx
Labels: ✨ Feature, 🐾준하

#193 [Feat]: 닉네임, 프로필 소개 수정
  src/components/modal/mypage/IntroEditModal.jsx
  src/components/modal/mypage/NicknameEditModal.jsx
Labels: ✨ Feature, 🐾준하

#192 [Fix] : 이슈 해결
  src/components/profile/ProfileBox.jsx
  src/components/profile/ProfileBox.style.js
  src/components/signup/SignUpMyInfo.jsx
  src/pages/mypage/edit/MyPageEdit.jsx
  src/pages/profile/ProfilePage.style.js
  src/pages/signup/SignUp.style.js
Labels: 🎨 Html&css, 🐞 BugFix, 🪐수진

#197 Feat: 캘린더 여정 작성 로직 및 스타일 수정
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/modal/journeyEdit/JourneyEditModal.jsx
  src/components/schedules/SchedulesView.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.style.js
Labels: ✨ Feature, 🎨 Html&css, 💗다인

#199 [Feat] : 시그니처 작성페이지 페이지 이동, 삭제 기능 (시그니처 title width 조정)
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Editor.style.js
  src/pages/signature/write/Page.jsx
  src/store/useSignatureWrite.jsx
Labels: ✨ Feature, 🎨 Html&css, 💗다인

#207 [Feat] 반응형 수정
  src/components/calendar/TravelCalendar.jsx
  src/components/explore/Preview.jsx
  src/components/mate/MateBox.style.js
  src/components/preview/Preview.jsx
  src/components/preview/Preview.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/signature/main/MySignaturePage.style.js
Labels: ✨ Feature, 👑용민

#210 [Style] : 메이트 탐색 디자인 변경, 스크롤바 수정, 알림 스타일 수정
  src/components/explore/SignatureSearchSlider.jsx
  src/components/explore/SignatureSearchSlider.style.js
  src/components/mate/skeleton/MateBoxSkeleton.jsx
  src/components/mate/skeleton/MateBoxSkeleton.style.js
  src/components/mate/skeleton/MateRecsys.style.js
  src/components/mate/skeleton/MateRecsysSkeleton.jsx
  src/components/notification/NotificationPage.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
Labels: 🎨 Html&css, 💗다인

#215 [Style] : 하루일지, 프로필 스켈레톤 UI 구현
  src/components/notification/skeleton/Notification.style.jsx
  src/components/notification/skeleton/NotificationSkeleton.jsx
  src/pages/dailyRecord/List/DailyRecordListPage.jsx
  src/pages/dailyRecord/List/skeleton/DailyRecordListSkeleton.jsx
  src/pages/dailyRecord/List/skeleton/DailyRecordListSkeleton.style.js
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/edit/skeleton/DailyRecordEditSkeleton.jsx
  src/pages/dailyRecord/edit/skeleton/DailyRecordEditSkeleton.style.js
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/mypage/diary/MyDiary.jsx
  src/pages/mypage/skeleton/DiarySkeleton.jsx
  src/pages/mypage/skeleton/DiarySkeleton.style.js
  src/pages/notification/Notification.jsx
  src/pages/profile/ProfilePage.jsx
  src/pages/profile/skeleton/ProfileSkeleton.jsx
  src/pages/profile/skeleton/ProfileSkeleton.style.js
Labels: 🎨 Html&css, 💗다인

#218 [Style] : 탐색 페이지 스켈레톤 스타일 수정
  src/components/explore/skeleton/SignatureSearchPreviewSkeleton.jsx
  src/components/explore/skeleton/SignatureSearchPreviewSkeleton.style.js
  src/components/preview/skeleton/PreviewSkeleton.style.js
Labels: 🎨 Html&css, 💗다인

#213 Style : 로그인 버튼 수정
  public/images/Google.svg
  public/images/Kakao.svg
  src/App.jsx
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KakaoLoginButton.jsx
  src/components/login/LoginButton.jsx
  src/components/login/SnsLoginButton.style.js
  src/pages/login/Login.jsx
  src/pages/login/Login.style.js
Labels: 🎨 Html&css, 🪐수진

#219 [Fix] : 이슈 수정
  src/components/comment/signature/commentInput/SignatureInput.style.js
  src/components/explore/SignatureSearchSlider.jsx
  src/components/login/SnsLoginButton.style.js
  src/components/mypage/MypageInfo.style.js
  src/components/preview/Preview.style.js
  src/pages/explore/ExplorePage.style.js
  src/pages/mate/Mate.style.js
  src/pages/mate/look/MateLook.style.js
  src/pages/mate/main/MateMain.jsx
  src/pages/mate/main/MateMain.style.js
  src/pages/mate/ruleWrite/MateRuleWrite.jsx
  src/pages/mate/ruleWrite/MateRuleWrite.style.js
  src/pages/signature/post/SignaturePost.style.js
Labels: 🎨 Html&css, 🐞 BugFix, 🪐수진

#223 [Feat] : 로그인 페이지 비행기 ✈✈
  public/images/airplane.svg
  public/images/background.svg
  src/mocks/handlers/signature.js
  src/pages/login/Login.jsx
  src/pages/login/Login.style.js
Labels: ✨ Feature, 🪐수진

#225 [Fix] : 이슈 해결
  src/components/banner/Banner.style.js
  src/components/bottomSheet/BottomScrollPage.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/comment/mate/commentInput/MateCommentInput.style.js
  src/components/mate/Search.jsx
  src/components/mate/TeamContainer.style.js
  src/components/navbar/Navbar.jsx
  src/index.css
  src/pages/home/Home.style.js
  src/pages/map/Map.style.js
  src/pages/mate/main/MateMain.jsx
  src/pages/mate/ruleCheck/MateRuleCheck.style.js
  src/pages/mate/ruleCheck/MateRuleDetailCheck.style.js
  src/pages/mate/ruleEdit/RuleEdit.jsx
  src/pages/mate/ruleEdit/RuleEdit.style.js
  src/utils/randomColor.js
Labels: 🐞 BugFix, 🪐수진

#229 Fix : 노션페이지 연결
  src/constants/subcategory.js
Labels: ✨ Feature, 🪐수진

#228 [Style] : 하루일지 상세 페이지 스켈레톤 UI 적용
  src/pages/dailyRecord/DailyRecordPage.jsx
  src/pages/dailyRecord/List/DailyRecordListPage.jsx
Labels: 🎨 Html&css, 💗다인

#234 [Feat] : 텍스트 black 스타일 수정, 각 페이지 로그인 확인
  src/components/bottomSheet/BottomDetailScrollPage.style.js
  src/components/bottomSheet/BottomScrollPage.style.js
  src/components/calendar/TravelCalendar.jsx
  src/components/calendar/TravelCalendar.style.js
  src/components/main/LoginBanner.jsx
  src/components/mate/Search.jsx
  src/components/modal/Modal.style.js
  src/components/mypage/Category.jsx
  src/components/navbar/Navbar.jsx
  src/components/profile/ProfileBox.style.js
  src/components/schedules/SchedulesView.jsx
  src/index.css
  src/pages/dailyRecord/edit/DailyRecordEdit.style.js
  src/pages/mate/main/MateMain.jsx
  src/pages/mate/main/MateMain.style.js
  src/pages/mate/ruleEdit/RuleEdit.style.js
  src/pages/mate/ruleWrite/MateRuleWrite.style.js
  src/pages/mypage/diary/MyDiary.jsx
  src/pages/quitUserPage/QuitUserPage.jsx
  src/pages/quitUserPage/QuitUserPage.style.js
  src/pages/signature/SignaturePage.jsx
  src/pages/signature/main/MySignaturePage.jsx
Labels: ✨ Feature, 💗다인

#238 Feat: 하루일지 없을 때 내 하루일지 확인 페이지 스타일링
  public/images/diary.webp
  src/pages/mypage/diary/MyDiary.jsx
  src/pages/mypage/diary/noDiary/NoDiaryPage.jsx
  src/pages/mypage/diary/noDiary/NoDiaryPage.style.js
Labels: ✨ Feature, 🎨 Html&css, 💗다인

#240 [Feat] : 자잘한 버그 수정 및 로딩처리
  public/images/diary.webp
  public/images/location.svg
  src/components/comment/mate/commentInput/MateCommentInput.jsx
  src/components/comment/signature/commentInput/SignatureCommentInput.jsx
  src/components/main/LoginBanner.jsx
  src/components/mypage/MypageInfo.jsx
  src/components/profile/ProfileBox.style.js
  src/pages/dailyRecord/edit/DailyRecordEdit.style.js
  src/pages/dailyRecord/edit/DailyRecordEditPage.jsx
  src/pages/dailyRecord/write/DailyRecordWrite.jsx
  src/pages/dailyRecord/write/DailyRecordWritePage.style.js
  src/pages/mate/look/MateLook.jsx
  src/pages/mate/look/MateLook.style.js
  src/pages/mate/ruleCheck/MateRuleDetailCheck.jsx
  src/pages/mate/ruleCheck/MateRuleDetailSkeleton/MateRuleDetailSkeleton.jsx
  src/pages/mate/ruleCheck/MateRuleDetailSkeleton/MateRuleDetailSkeleton.style.js
  src/pages/mate/ruleEdit/RuleEdit.jsx
  src/pages/mate/ruleEdit/RuleEdit.style.js
  src/pages/mate/ruleEdit/RuleEditSkeleton/RuleEditSkeleton.jsx
  src/pages/mate/ruleEdit/RuleEditSkeleton/RuleEditSkeleton.style.js
  src/pages/mate/ruleWrite/MateRuleWrite.jsx
  src/pages/mate/ruleWrite/MateRuleWrite.style.js
  src/pages/mypage/diary/MyDiary.jsx
  src/pages/mypage/diary/noDiary/NoDiaryPage.jsx
  src/pages/mypage/diary/noDiary/NoDiaryPage.style.js
  src/pages/signature/edit/Editor.jsx
  src/pages/signature/edit/SignatureEdit.style.js
  src/pages/signature/write/Editor.jsx
  src/pages/signature/write/Editor.style.js
Labels: ✨ Feature, 🎨 Html&css, 💗다인
